DROP TABLE IF EXISTS MessageSocketQueue;
CREATE TABLE MessageSocketQueue (
    MessageID INTEGER PRIMARY KEY AUTOINCREMENT,
    Data TEXT
);

CREATE TABLE IF NOT EXISTS Checksums (
     DicKey TEXT PRIMARY KEY,
     Checksum TEXT NOT NULL
);